# MasterDnsVPN Server Config Template
DOMAIN = ["v.yourdomain.com"]
UDP_HOST = "0.0.0.0"
UDP_PORT = 53
DATA_ENCRYPTION_METHOD = 2 # ChaCha20
ENCRYPTION_KEY_FILE = "encrypt_key.txt"
LOG_LEVEL = "INFO"
